### ISSUE TITLE
Pressing enter does not help

### ISSUE THREAD

**Issue by ChillerDragon** [gerdoe-jr/tw-econ-tui#1]
Helo step bro! Im stuck in greeting screen!!!

**Comment by ChillerDragon** [comment]
```
$ uname -a
Linux arch 6.2.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 18 Mar 2023 01:06:36 +0000 x86_64 GNU/Linux
$ cargo run
```

I use the gnome-terminal seems like it does not catch me pressing enter or ctrl+c for that matter.

![image](https://user-images.githubusercontent.com/20344300/227726796-3a60d608-9329-4380-8b3d-1211ecd58055.png)

**Comment by gerdoe-jr** [comment]
@ChillerDragon Try it out again xd

**Comment by ChillerDragon** [comment]
Fixed. But also this tool is unusable slow to respond. So slow that half the letters get lost when pasting in an address.

**Comment by gerdoe-jr** [comment]
Haven't tested *nix terminals yet, it works *almost* good on win10. Will also add `tui-input` to make input blocks smoother
